'use client'

import Head from 'next/head'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


export default function Home() {

  return (
    <>
      <Head>
        <title>Login System</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <div className="grid grid-cols-2 h-screen">
        <section className="bg-blue-700 text-center text-blue-500 flex items-center justify-center">
          <div>
            <h1 className="text-xl font-bold leading-tight tracking-tight text-blue-500 md:text-9xl dark:text-white">
              HELLO DOOR
            </h1>
            {/* <img src="/vercel.svg" alt="Left Background" className="w-full" /> */}
          </div>
        </section>
        <section className="bg-white text-center text-blue-600 flex items-center justify-center">
          <div className="w-full max-w-md">
            <div className="p-6 space-y-4 md:space-y-6 sm:p-8">
              <h1 className="text-xl font-bold leading-tight tracking-tight text-blue-600 md:text-2xl dark:text-white">
                HELLO DOOR
              </h1>
              <form className=" space-y-4 md:space-y-6" action="#">
                <div className='text-left'>
                  <label htmlFor="email" className="block mb-2 text-sm font-medium text-blue-900 dark:text-white">Your email</label>
                  <input type="email" name="email" id="email" className="bg-blue-50 border border-blue-300 text-blue-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-blue-700 dark:border-blue-600 dark:placeholder-blue-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="name@gmail.com"  />
                </div>
                <div className='text-left'>
                  <label htmlFor="password" className="block mb-2 text-sm font-medium text-blue-900 dark:text-white">Password</label>
                  <input type="password" name="password" id="password" placeholder="••••••••" className="bg-blue-50 border border-blue-300 text-blue-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-blue-700 dark:border-blue-600 dark:placeholder-blue-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"  />
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-start">
                    <div className="flex items-center h-5">
                      <input id="remember" aria-describedby="remember" type="checkbox" className="w-4 h-4 border border-blue-300 rounded bg-blue-50 focus:ring-3 focus:ring-primary-300 dark:bg-blue-700 dark:border-blue-600 dark:focus:ring-primary-600 dark:ring-offset-blue-800"  />
                    </div>
                    <div className="ml-3 text-sm">
                      <label htmlFor="remember" className="text-blue-500 dark:text-blue-300">Remember me</label>
                    </div>
                  </div>
                  <a href="#" className="text-sm font-medium text-primary-600 hover:underline dark:text-primary-500">Recovery Password</a>
                </div>
                <button type="submit" className="w-full text-white bg-blue-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Sign in</button>
              </form>
            </div>
          </div>
        </section>
      </div>
      <ToastContainer />
    </>
  )
}
